
(in-package :lambda-lifter)

(defun in-range-p (metadata x y)
  (with-meta-bind (metadata width height)
    (and (>= x 1)
	 (>= y 1)
	 (<= x width)
	 (<= y height))))

(defmacro rock-move-values (world objects path metadata rx ry rx-new ry-new &optional (non-map-update nil))
  `(values (lambda (x y)
	     (cond ((and (= x ,rx)
			 (= y ,ry))
		    nil)
		   ((and (= x ,rx-new)
			 (= y ,ry-new))
		    :rock)
		   (t (funcall ,world x y))))
	   (lambda (type)
	     (case type
	       (:rock (cons (complex ,rx-new ,ry-new)
			    (remove (complex ,rx ,ry) (funcall ,objects :rock))))
	       (:injury (if ,non-map-update
			    nil
                            (with-robot-coords (rbx rby) objects
			      (when (and (= ,rx-new rbx)
					 (= (- ,ry-new 1) rby))
				t))))
	       (t (funcall ,objects type))))
	   ,path
	   ,metadata))

(defun rock-fall (iworld imetadata rx ry)
  (lambda (world objects path metadata)
    (let ((rx-under rx)
	  (ry-under (- ry 1)))
      (when (and (in-range-p imetadata rx-under ry-under)
		 (eq nil (funcall iworld rx-under ry-under)))
	(rock-move-values world objects path metadata rx ry rx-under ry-under)))))

(defun rock-slide-right (iworld imetadata rx ry)
  (lambda (world objects path metadata)
    (let ((rx-under rx)
	  (ry-under (- ry 1))
	  (rx-right (+ rx 1))
	  (ry-right ry)
	  (rx-right-under (+ rx 1))
	  (ry-right-under (- ry 1)))
      (when (and (in-range-p imetadata rx-right-under ry-right-under)
		 (eq :rock (funcall iworld rx-under ry-under))
		 (eq nil (funcall iworld rx-right ry-right))
		 (eq nil (funcall iworld rx-right-under ry-right-under)))
	(rock-move-values world objects path metadata rx ry rx-right-under ry-right-under)))))

(defun rock-slide-left (iworld imetadata rx ry)
  (lambda (world objects path metadata)
    (let ((rx-under rx)
	  (ry-under (- ry 1))
	  (rx-right (+ rx 1))
	  (ry-right ry)
	  (rx-right-under (+ rx 1))
	  (ry-right-under (- ry 1))
	  (rx-left (- rx 1))
	  (ry-left ry)
	  (rx-left-under (- rx 1))
	  (ry-left-under (- ry 1)))
      (when (and (in-range-p imetadata rx-left-under ry-left-under)
		 (in-range-p imetadata rx-right-under ry-right-under)
		 (eq :rock (funcall iworld rx-under ry-under))
		 (not (eq nil (funcall iworld rx-right ry-right)))
		 (not (eq nil (funcall iworld rx-right-under ry-right-under)))
		 (eq nil (funcall iworld rx-left ry-left))
		 (eq nil (funcall iworld rx-left-under ry-left-under)))
	(rock-move-values world objects path metadata rx ry rx-left-under ry-left-under)))))

(defun rock-slide-right-over-lambda (iworld imetadata rx ry)
  (lambda (world objects path metadata)
    (let ((rx-under rx)
	  (ry-under (- ry 1))
	  (rx-right (+ rx 1))
	  (ry-right ry)
	  (rx-right-under (+ rx 1))
	  (ry-right-under (- ry 1)))
      (when (and (in-range-p imetadata rx-right-under ry-right-under)
		 (eq :lambda (funcall iworld rx-under ry-under))
		 (eq nil (funcall iworld rx-right ry-right))
		 (eq nil (funcall iworld rx-right-under ry-right-under)))
	(rock-move-values world objects path metadata rx ry rx-right-under ry-right-under)))))

(defun rock-push-left (rx ry)
  (lambda (world objects path metadata)
    (let ((rx-left (- rx 1))
	  (ry-left ry))
      (when (and (in-range-p metadata rx-left ry-left)
		 (eq nil (funcall world rx-left ry-left)))
	(rock-move-values world objects path metadata rx ry rx-left ry-left t)))))

(defun rock-push-right (rx ry)
  (lambda (world objects path metadata)
    (let ((rx-right (+ rx 1))
	  (ry-right ry))
      (when (and (in-range-p metadata rx-right ry-right)
		 (eq nil (funcall world rx-right ry-right)))
	(rock-move-values world objects path metadata rx ry rx-right ry-right t)))))

(defun rock-can-be-pushed-left (world metadata rx ry)
  (let ((rx-left (- rx 1))
	(ry-left ry))
    (and (in-range-p metadata rx-left ry-left)
	 (eq nil (funcall world rx-left ry-left)))))

(defun rock-can-be-pushed-right (world metadata rx ry)
  (let ((rx-right (+ rx 1))
	(ry-right ry))
    (and (in-range-p metadata rx-right ry-right)
	 (eq nil (funcall world rx-right ry-right)))))

(defun rock-move (iworld imetadata rx ry)
  (lambda (world objects path metadata)
    (or (funcall (rock-fall iworld imetadata rx ry) world objects path metadata)
	(funcall (rock-slide-right iworld imetadata rx ry) world objects path metadata)
	(funcall (rock-slide-left iworld imetadata rx ry) world objects path metadata)
	(funcall (rock-slide-right-over-lambda iworld imetadata rx ry) world objects path metadata)
	(values world objects path metadata))))

(defun rocks-move (world objects path metadata)
  (let ((world~ world)
	(objects~ objects)
	(path~ path)
	(metadata~ metadata))
    (with-meta-bind (metadata width)
      (iter (for rock-coord in (sort (funcall objects :rock) #'<
				     :key (lambda (c) (+ (realpart c) (* (imagpart c) width)))))
	(multiple-value-setq (world~ objects~ path~ metadata~)
	  (funcall (rock-move world metadata (realpart rock-coord) (imagpart rock-coord))
		   world~ objects~ path~ metadata~))))
    (values world~ objects~ path~ metadata~)))
